### PR TITLE
Setup coverage

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Setup coverage, replace #34

*Voilà Voilà* (**Bis**)

(my response to your future message: https://www.youtube.com/watch?v=WQ5_fya5IdI)

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
last step is to log to coveralls with your github account and activate the repo :)

**Comment by johnbrett** [comment]
Cheers for this @AdrieanKhisbe, currently syncing repos on coveralls - taking a while though! This and https://github.com/johnbrett/calibrate/pull/36 were great additions! I like to practice OPEN open source (https://gist.github.com/substack/e205f5389890a1425233) on my repos - would you like commit access on Calibrate? :)

**Comment by AdrieanKhisbe** [comment]
Would be pleased to contribute :)

Was indeed considering at some point implementing the feature to be able to customize *success* structure

**Comment by johnbrett** [comment]
You should have access now! That'd be a cool feature alright :) PR me on anything, great opportunity to learn!

**Comment by AdrieanKhisbe** [comment]
Yep will do!
Will work on a dedicated branch :)

**Pull request merged**
