### PR TITLE
Hapi v17

### PR DESCRIPTION
**Pull request by estebanprimost**
This PR adds support for Hapi v17.
* Replaced `decorate` method by `hapi`.
* Tests updated.
* Upgraded almost all dependencies.
* Updated node versions.

### CODE REVIEW

**Comment by estebanprimost** [comment]
#82 @tinchoz49

**Comment by johnbrett** [comment]
This is awesome work @estebanprimost! Thank you!

**Comment by estebanprimost** [comment]
Thanks, @johnbrett. This library is very useful to me. 
Remember to upgrade the major version!!! This is a very breaking change.

**Comment by johnbrett** [comment]
That is absolutely is :D Published as v4.0.0. 

This is fantastic work - would you like commit access to the repo if you have further improvements you'd like to make ?

**Comment by estebanprimost** [comment]
Cool, that would be great, I'm thinking on improving the README (usage, etc) and other stuff. But it's ok with PRs from my fork too.

**Comment by johnbrett** [comment]
Invite sent @estebanprimost!

**Pull request merged**
