### PR TITLE
[Calibrate] Update dependencies, ensure tests run & pass

### PR DESCRIPTION
**Pull request by iwasrobbed**
Hi there 👋 I used this a while back and went to use it on a new project but first wanted to make sure it used the latest and greatest `@hapi/*` variants.

Thanks!

### CODE REVIEW

**Comment by iwasrobbed** [comment]
It looks like you're supporting old versions of `node` on the travis tests; please let me know if you plan to continue to do so otherwise the tests will fail here

**Comment by johnbrett** [comment]
Hey @iwasrobbed thanks for this PR! I do not plan to support older versions of Node, can you remove them?

**Comment by johnbrett** [comment]
I've also added you as a maintainer of the repo, so if you want to make further PRs you can now have the power to merge em too!

**Comment by johnbrett** [comment]
@iwasrobbed v4.1.0 published to npm! Thanks! 🍾

**Pull request merged**
